// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.CheerUpMyHero.CloudCode
{
    public partial class GachaBannerClientInfo
    {
        public string BannerId;
        public int PityThreshold;

        [Preserve]
        public GachaBannerClientInfo ()
        {
        }
    }
}