// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.CheerUpMyHero.CloudCode
{
    public enum Rarity
    {
        Epic,
        Rare,
        Common,
    }
}
