// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.CheerUpMyHero.CloudCode
{
    public partial class ResultUnit
    {
        public int UnitId;
        public Rarity Rarity;

        [Preserve]
        public ResultUnit ()
        {
        }
    }
}