// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.CheerUpMyHero.CloudCode
{
    public partial class GachaResult
    {
        public List<ResultUnit> ResultUnit;
        public int CurrentPityCount;
        public int UserCurrency;

        [Preserve]
        public GachaResult ()
        {
        }
    }
}