// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GachaModuleV2Bindings
    {
        readonly ICloudCodeService k_Service;
        public GachaModuleV2Bindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<CheerUpMyHero.CloudCode.GachaResult> DrawGachaOne(string bannerId)
        {
            return await k_Service.CallModuleEndpointAsync<CheerUpMyHero.CloudCode.GachaResult>(
                "GachaV2",
                "DrawGachaOne",
                new Dictionary<string, object>()
                {
                    {"bannerId", bannerId},
                });
        }

        public async Task<CheerUpMyHero.CloudCode.GachaResult> DrawGachaTen(string bannerId)
        {
            return await k_Service.CallModuleEndpointAsync<CheerUpMyHero.CloudCode.GachaResult>(
                "GachaV2",
                "DrawGachaTen",
                new Dictionary<string, object>()
                {
                    {"bannerId", bannerId},
                });
        }
    }
}
