// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class EconomyModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public EconomyModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> ChangeEconomyResource(string currencyId, int amount)
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "Economy",
                "ChangeEconomyResource",
                new Dictionary<string, object>()
                {
                    {"currencyId", currencyId},
                    {"amount", amount},
                });
        }
    }
}
