// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GachaModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public GachaModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<int> DrawGachaItem()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "Gacha",
                "DrawGachaItem",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<List<int>> DrawGachaItemTen()
        {
            return await k_Service.CallModuleEndpointAsync<List<int>>(
                "Gacha",
                "DrawGachaItemTen",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<int> DrawPickUPItem()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "Gacha",
                "DrawPickUPItem",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
